import React from 'react';

interface TermsProps {
  onNavigate: (page: 'home' | 'privacy' | 'terms', hash?: string) => void;
}

export const Terms: React.FC<TermsProps> = ({ onNavigate }) => {
  return (
    <main>
      <section className="page-hero-section">
        <div className="container">
          <div className="section-header" style={{ marginBottom: '1rem' }}>
            <span className="section-tag purple">Legal & Terms</span>
            <h1 className="section-title">Terms of Service</h1>
            <p className="section-description">
              Last Updated: July 28, 2026 • Official Terms of Service for the Logvera Project
            </p>
          </div>
        </div>
      </section>

      <section className="legal-page-section">
        <div className="container">
          <div className="legal-card">
            <div className="legal-highlight-box">
              <strong>Development Notice:</strong> Logvera is a personal software engineering project designed for software discussion analysis. It is currently under active local development, operates strictly on local developer infrastructure, and is not offering commercial public subscriptions or publicly hosted multi-tenant services.
            </div>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing this website or inspecting documentation related to Logvera, you agree to comply with these Terms of Service. If you do not agree with any part of these terms, please do not use or reference the application.</p>

            <h2>2. Permitted & Acceptable Use</h2>
            <p>Logvera is intended solely for personal engineering research, analytical demonstration, and customer feedback issue detection. Permitted usage boundaries include:</p>
            <ul>
              <li>Analyzing publicly available discussions regarding software tools to identify technical issues and user sentiment.</li>
              <li>Inspecting local analytical reports and dashboards generated by Logvera’s data aggregation pipeline.</li>
              <li>Evaluating API compliance and security protocols for Google YouTube Data API quota verification.</li>
            </ul>

            <h2>3. YouTube API Services Compliance & Third-Party Policy Agreement</h2>
            <p>Logvera relies on official YouTube API Services to retrieve public discussion content. By using Logvera, users agree to be bound by:</p>
            <ul>
              <li>The official <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer">YouTube Terms of Service</a>.</li>
              <li>The <a href="https://developers.google.com/youtube/terms/api-services-terms-of-service" target="_blank" rel="noopener noreferrer">YouTube API Services Terms of Service</a>.</li>
              <li>The <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</a>.</li>
            </ul>
            <p>Users must not attempt to use Logvera to perform web scraping, download YouTube videos, modify YouTube content, or perform write actions on YouTube on behalf of users.</p>

            <h2>4. Intellectual Property & Significant Independent Value</h2>
            <p>All analytical algorithms, topic classification logic, sentiment scoring modules, and UI layout code developed for Logvera remain the intellectual property of the project developer. YouTube video titles, channel names, and public comment content accessed via the YouTube Data API belong to their respective creators and copyright holders and are accessed on a strictly read-only public basis.</p>

            <h2>5. Limitation of Liability & Warranty Disclaimer</h2>
            <p>Logvera is provided "AS IS" and "AS AVAILABLE" for personal research and local demonstration purposes without warranties of any kind, whether express or implied. The developer shall not be liable for any indirect, incidental, or consequential damages resulting from the local use of analytical outputs.</p>

            <h2>6. Modifications to Terms</h2>
            <p>The developer reserves the right to update these Terms of Service as the project evolves or as required by YouTube API Services Developer Policies.</p>

            <h2>7. Contact Information</h2>
            <p>If you have any questions regarding these Terms of Service or API compliance, please reach out:</p>
            <div className="contact-highlight-card">
              <p><strong>Developer Email:</strong> <a href="mailto:gsurya1412@gmail.com">gsurya1412@gmail.com</a></p>
              <p><strong>GitHub Repository:</strong> <a href="https://github.com/SuryaVirata/Logvera-reddit-Extarctor" target="_blank" rel="noopener noreferrer">github.com/SuryaVirata/Logvera-reddit-Extarctor</a></p>
              <p><strong>Project Website URL:</strong> <a href="https://logvera-lemon.vercel.app" target="_blank" rel="noopener noreferrer">https://logvera-lemon.vercel.app</a></p>
            </div>

            <div style={{ marginTop: '2rem' }}>
              <button onClick={() => onNavigate('home')} className="btn btn-secondary btn-sm">
                ← Back to Homepage
              </button>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};
